baseURL = "https://air-factories-2-0.github.io/af2-website/public/"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "it"
[languages]

  [languages.en]
    title = "Air Factories 2.0"
    contentDir = 'content/en'
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = 'Italian'
        url = ''

  [languages.it]
    title = "Air Factories 2.0"
    contentDir = 'content/it'

       [languages.it.menu]
        [[languages.it.menu.main]]
          name = 'English'
          url = 'en'



# The "title" of your website
title = "Air Factories 2.0"

[params]
    copyright = "© Air Factories 2.0"

    description = ""

    favicon = "images/favicon.png"

    images = ["images/cover-image.jpg"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Air Factories 2.0"


    [params.meta]
        keywords = "3D, printer, blockchain, ethereum, distributed app, dapp, factories, air factories"
